### ISSUE TITLE
Team Player page

### ISSUE THREAD

**Issue by Turjoe** [safwanrahman/itclub#2]
Page totally broken. need to fix. try to make it in list or grid format.

**Comment by safwanrahman** [comment]
Done! :) :+1: 
![firefox_screenshot_2015-04-05t09-22-30 100z](https://cloud.githubusercontent.com/assets/7114151/6996398/ac75a2f4-dba7-11e4-8226-5cf8d3fa540f.png)

**Comment by safwanrahman** [comment]
![screen shot 2015-04-05 at 15 26 26](https://cloud.githubusercontent.com/assets/7114151/6996411/c08f8d4e-dba8-11e4-9e92-796adb48f0f9.png)

**Comment by safwanrahman** [comment]
@Turjoe is it Ok?

**Comment by Turjoe** [comment]
yes okay
